name: grid_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  card_swiper: ^2.0.4
  flutter:
    sdk: flutter
  tutorial_coach_mark: ^1.2.9
  swipe_cards: ^2.0.0+1
  http: ^1.1.0
  widgetbook: ^3.1.0
  go_router: ^9.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
