name: grid_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  card_swiper: ^2.0.4
  feature_discovery: ^0.14.1
  flutter:
    sdk: flutter
  tutorial_coach_mark: ^1.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
